version: '3.9'

services:
  cube:
    build:
      context: /root/dockercalculator/cube
      dockerfile: /root/dockercalculator/cube/Dockerfile
    restart: always
    ports:
      - "8081:5000"

  square:
    build:
      context: /root/dockercalculator/Square
      dockerfile: /root/dockercalculator/Square/Dockerfile
    restart: always
    ports:
      - "8082:5000"

  fibonacci:
    build:
      context: /root/dockercalculator/fibonacci
      dockerfile: /root/dockercalculator/fibonacci/Dockerfile
    restart: always
    ports:
      - "8083:5000"

  front_end:
    build:
      context: /root/dockercalculator/front-end
      dockerfile: /root/dockercalculator/front-end/Dockerfile
    restart: always
    ports:
      - "8086:80"
    depends_on:
      - cube
      - square
      - fibonacci